import type { Plan } from "../types";

export const plans: Plan[] = [
  {
    id: "basico",
    nombre: "Básico",
    precio: "$1,490",
    precioRaw: 1490,
    periodo: "MXN / mes",
    sensores: "3 sensores incluidos",
    destacado: false,
    features: [
      "Dashboard analítico web",
      "Monitoreo IoT en tiempo real",
      "Alertas básicas por email",
      "Trazabilidad por lote con QR",
      "Hasta 50 lotes activos",
      "Soporte por correo (24h)",
    ],
    cta: "Comenzar prueba 30 días",
  },
  {
    id: "pro",
    nombre: "Pro",
    precio: "$3,990",
    precioRaw: 3990,
    periodo: "MXN / mes",
    sensores: "10 sensores incluidos",
    destacado: true,
    features: [
      "Todo lo del plan Básico",
      "Pronóstico de demanda con ML",
      "Integración con transportistas",
      "Reportes ESG mensuales",
      "Lotes ilimitados",
      "Soporte prioritario (4h)",
      "Capacitación al equipo",
    ],
    cta: "Comenzar prueba 30 días",
  },
  {
    id: "enterprise",
    nombre: "Enterprise",
    precio: "A cotizar",
    precioRaw: null,
    periodo: "según volumen",
    sensores: "Sensores ilimitados",
    destacado: false,
    features: [
      "Todo lo del plan Pro",
      "API completa para integración",
      "Multi-finca / multi-bodega",
      "Soporte 24/7 con SLA",
      "Consultoría dedicada (CSM)",
      "Certificaciones digitales premium",
      "On-premise opcional",
    ],
    cta: "Hablar con ventas",
  },
];
